### ISSUE TITLE
Change Zip4j in favor of commons-compress

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-spacelift#15]
UnZip tool is based on zip4j library. The problem is that sometimes the files are tar, gzip, 7z, or arj. I suggest to change zip4j to commons-compress which supports a lot of compress algorithms in order to be able to write some Tool like UnzipTool, UntarTool and so on and even a generic UnCompressTool which you set the algorithm to be used.

http://search.maven.org/#artifactdetails%7Corg.apache.commons%7Ccommons-compress%7C1.8.1%7Cjar

The good news is that this library is maintained as well (last version released is from May 2014.

Again if you agree I will implement the change.

Note: that I have never found this error because I download zip files but today it is the first time I have found this barrier.

Of course another approach is to use GZipIS but because we are already using zip4j we can drop it and add this library.

**Comment by kpiwko** [comment]
Closing, this was resolved by https://github.com/lordofthejars/arquillian-spacelift/commit/3301929a722c0a203e3416e7de6bcc3209cf6b61
