### ISSUE TITLE
Rename workingDir to workingDirectory in CommandTool.

### ISSUE THREAD

**Issue by TadeasKriz** [arquillian/arquillian-spacelift#20]

**Comment by kpiwko** [comment]
Note, probably would be worth to keep workingDir(x) available for some time to make sure we won't break compatibility with existing code.

**Comment by TadeasKriz** [comment]
Sure, we might leave it in until first beta release. I'd just annotate it with `@Deprecated` for clarity.

**Comment by kpiwko** [comment]
+1

**Comment by kpiwko** [comment]
Fixed in https://github.com/arquillian/arquillian-spacelift/commit/b6b99690fe8bcb0158f77746036fe2ef2c0b03ca
