### ISSUE TITLE
Add convenience method workingDirectory(File) into CommandTool.

### ISSUE THREAD

**Issue by TadeasKriz** [arquillian/arquillian-spacelift#21]

**Comment by kpiwko** [comment]
Does it make sense to rather use workingDirectory(Object) and fail runtime if it's not File nor CharSequence?

**Comment by TadeasKriz** [comment]
I'd rather see something like 
```
class CommandTool {
...
public static final File WORKING_DIRECTORY_NONE = null;
...
}
```

than leaving this for runtime (the name should be shorter). You would then use:

```
Tasks.prepare(CommandTool.class)
          .workingDirectory(CommandTool.WORKING_DIRECTORY_NONE)
```

**Comment by kpiwko** [comment]
that could we CommandTool.CURRENT_PROCESS_DIRECTORY

http://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#directory%28java.io.File%29

**Comment by kpiwko** [comment]
Fixed in https://github.com/arquillian/arquillian-spacelift/commit/b6b99690fe8bcb0158f77746036fe2ef2c0b03ca
